### ISSUE TITLE
Card font

### ISSUE THREAD

**Issue by Tatsuwashi** [gbuela/kanjiryokucha#54]
Hello! I absolutely love the app!

However, the font on the back of the cards that show the kanji has serious issues. It is showing slightly incorrect kanji and also outright mistakes. I can’t tell for sure, but I think most of the issues would be taken care of if a different font was used.

Thank you for your time.

**Comment by gbuela** [comment]
Hi, can you provide an example where you find issues? Thanks

**Comment by Tatsuwashi** [comment]
Hello,

Here are some screenshots that I took. These are just examples from the first 100 kanji. I think that changing the installed font will fix most of the problems, but I am not sure. I am using this app on an iPad.

Thank you for your work!

Sincerely,

David Fulvio


[Image][Image][Image][Image][Image]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gbuela** [comment]
Hi! the images don't show up. Please try attaching directly on a comment in github instead of replying by email. Thanks!

**Comment by Tatsuwashi** [comment]
[
![7cd99d77-fdd5-48a3-ba83-d4e269f08635](https://user-images.githubusercontent.com/42594899/44556860-b2a5f400-a776-11e8-9ee4-a8f2d0ce762b.png)
![b872faa4-a324-4167-b1e3-181ef9016f21](https://user-images.githubusercontent.com/42594899/44556861-b2a5f400-a776-11e8-8501-e98b145d1781.png)
![faffde19-fd31-4243-b81c-e6701a7ad1b5](https://user-images.githubusercontent.com/42594899/44556862-b2a5f400-a776-11e8-8fc5-eb629b89eb99.png)
![d8a93fe1-2b0e-4432-88e6-e3bc0083da9e](https://user-images.githubusercontent.com/42594899/44556863-b33e8a80-a776-11e8-83c2-d2cd6ade54e0.png)
![58ae0be7-bd80-44a3-af01-10c663f46f31](https://user-images.githubusercontent.com/42594899/44556865-b33e8a80-a776-11e8-8355-f97832c4cd01.png)




](url)

**Comment by gbuela** [comment]
Yes, it's a font issue. I'll see if I can get a better one.

**Comment by gbuela** [comment]
Hi. I reproduced the issue on the simulator but on my iPhone the characters show correctly. Somebody describes the iPad issue here:
http://www.sinosplice.com/life/archives/2012/02/28/unmixing-chinese-and-japanese-fonts-on-the-ipad-and-mac-os
except they are having the opposite problem, japansese is showing when they expected chinese. Can you see if you apply the same workaround (switching the languages)?

**Comment by Tatsuwashi** [comment]
Hi,


I am seeing the same incorrect characters on my phone and ipad.


This is not a case of seeing a Chinese variant. This kanji is just displaying wrong. It is not an actual kanji.


Can you change the font (not the language) that is used in the app? What font is being used now?


Thanks,


David Fulvio



________________________________

**Comment by gbuela** [comment]
Hi, I was able to reproduce the issue on my device and fix it. It was initially displaying the characters correctly while my main language was Spanish and my preferred languages were Spanish / English / Japanese in that order. I set my iPhone language to English and removed the other two. Then I started seeing the characters as in your screenshots.
After just adding Japanese in preferred languages, the app starts showing it correctly. Can you try it?
![img_1112](https://user-images.githubusercontent.com/19420015/45900942-9fa73380-bdb7-11e8-92f3-4e25c0f2c420.jpg)
The font is Helvetica Neue, but apparently this is not a mere font issue.

**Comment by Tatsuwashi** [comment]
Hi!


I switched my ipad language to Japanese and it displayed correctly.

I switched back to English and it still displayed correctly.


So, it is working for me now.


I am excited to get studying. Thank you for your time!


Sincerely,


David Fulvio

________________________________
