### ISSUE TITLE
Dictionary Entries

### ISSUE THREAD

**Issue by MWickliffe2** [gbuela/kanjiryokucha#55]
Brand spanking new to github, apologies in advance. I haven’t been able to access any dictionary entries. Options > Study Page > Dictionary > nothing. I’m running app on iPhone 7, iOS 12.1.2. Thanks.

**Comment by gbuela** [comment]
Yup, the Study Page feature is more of a quick look, the kanji koohii site is not fully functional within the app. You can use the "Open in Safari" button at the bottom to switch to the full fledged site. 
Not all the functionality of the site is available for external apps.
