### ISSUE TITLE
App crashes when logging in (v3.0)

### ISSUE THREAD

**Issue by ghost** [gbuela/kanjiryokucha#56]
I just installed v3.0 on my iPad mini 2 running iOS 12.4.6 and the app crashes everytime on startup when trying to log in.  I tried uninstalling and reinstalling the app, and also restarted the iPad.

**Comment by gbuela** [comment]
Hi @gdsjlign, were you using a previous version before or is 3.0 the first ever version you install on the iPad?

**Comment by ghost** [comment]
I had v2.1 installed and then uninstalled it at some point before trying v3.0 yesterday.

**Comment by ghost** [comment]
Here is the crash report: 
[KanjiRyokucha-2020-05-09-100405.zip](https://github.com/gbuela/kanjiryokucha/files/4604178/KanjiRyokucha-2020-05-09-100405.zip)

**Comment by gbuela** [comment]
Thanks, I was able to reproduce it for iPad with OS < 13. I'll get to fix it ASAP.

**Comment by gbuela** [comment]
Fixed on 3.1. It may take a few days to be out.
Thanks for the report @gdsjlign

**Comment by ghost** [comment]
Appreciate the quick fix, thanks!

**Comment by gbuela** [comment]
@gdsjlign everything OK with 3.1?

**Comment by ghost** [comment]
@gbuela Yep, works for me!
