### ISSUE TITLE
Add stroke count to cards

### ISSUE THREAD

**Issue by ghost** [gbuela/kanjiryokucha#57]
It would be nice if the stroke count for the kanji was listed on the backside of the card like it is on Kanji Koohii, especially since it should be checked everytime you learn/review a kanji according to Heisig.  Kanji Alive doesn't support a lot of kanji so I usually have to open up the card on Kanji Koohii or Jisho to get the stroke count.  Also, is there another public API that supports stroke order animations for all 3000 RTK kanji, and not just 1235?

**Comment by gbuela** [comment]
I have to check if stroke count is available in the Koohii API... as for Kanji Alive it is frustrating that so many kanji are missing, but it was so practical for integrating into the app. Since then I haven't researched for alternatives again.

**Comment by gbuela** [comment]
fixed in 3.2
